# Generated by Django 5.1.7 on 2025-05-13 21:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_cart_user_alter_item_seller_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('PURCHASED', 'Purchased')], default='IN_STOCK', max_length=12),
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_added', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status_added', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('PURCHASED', 'Purchased')], max_length=12)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
    ]
